name: Check linting
description: This will lint all changed files (relative to `main`)

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install compatible npm version
      shell: bash
      run: npm install npm@8.5.5 -g
    
    - name: Install npm packages
      shell: bash
      run: npm ci
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v31
      with:
        separator: ","
        old_new_files_separator: ","
        files_separator: ","
        files: "**/*.ts,**/*.tsx,**/*.js,**/*.jsx"

    - name: List changed files
      id: fix-changed-paths
      shell: bash
      run: |
        OUTPUT=""
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
          OUTPUT+=$(printf "%q" "$file" | tr "," " ")
        done
        echo "escaped-file-paths=$OUTPUT" >> $GITHUB_OUTPUT

    - name: Check linting in changed files
      shell: bash
      run: npx eslint --quiet --ext .js,.ts,.tsx ${{ steps.fix-changed-paths.outputs.escaped-file-paths }}
