name: Deploy to ECS
description: Action to build and deploy Docker image to AWS ECS

inputs:
  region:
    description: 'AWS Region'
    required: true
  ecr_repository:
    description: 'ECR Repository'
    required: true
  ecs_task_family:
    description: 'ECS Task definition family'
    required: true
  ecs_service:
    description: 'ECS Service'
    required: true
  ecs_cluster:
    description: 'ECS cluster name'
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Access Key'
    required: true
  build_target:
    description: 'Docker build target'
    default: 'production'
  build_arg:
    description: 'Docker build arg'
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: Heja/actions/configure-aws@v3
      with:
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build docker image
      shell: bash
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository }}
        IMAGE_TAG: ${{ github.sha }}
        TARGET: ${{ inputs.build_target }}
        BUILD_ARG: ${{ inputs.build_arg }}
      run: |
        DOCKER_BUILDKIT=1 docker build ${{ (inputs.build_arg !== '' && [ '--build-args', $inputs.build_arg] || '') }} --target=$TARGET -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        echo "::set-output name=tagged_image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output name=latest_image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"

    - name: Push docker image
      shell: bash
      id: push-image
      env:
        TAGGED_IMAGE: ${{ steps.build-image.outputs.tagged_image }}
        LATEST_IMAGE: ${{ steps.build-image.outputs.latest_image }}
      run: |
        docker push $TAGGED_IMAGE
        docker push $LATEST_IMAGE

    - name: Deploy task definition
      uses: Heja/actions/deploy-ecs-service@v3
      with:
        ecs_task_family: ${{ inputs.ecs_task_family }}
        ecs_service: ${{ inputs.ecs_service }}
        ecs_cluster: ${{ inputs.ecs_cluster }}
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.region }}
